_check_yadm_status () {
	if [[ $(yadm status -s) ]]; then
		print -P '%B%F{magenta}There are local configuration changes. Yadm sync required.%f%b'
	fi
}

autoload -Uz add-zsh-hook
add-zsh-hook precmd _check_yadm_status

# Aliases
y=yadm
ya='yadm add'
yap='yadm apply'
yapa='yadm add --patch'
yau='yadm add --update'
yb='yadm branch'
yba='yadm branch -a'
ybd='yadm branch -d'
ybda='yadm branch --no-color --merged | command grep -vE "^(\*|\s*(master|develop|dev)\s*$)" | command xargs -n 1 yadm branch -d'
ybl='yadm blame -b -w'
ybnm='yadm branch --no-merged'
ybr='yadm branch --remote'
ybs='yadm bisect'
ybsb='yadm bisect bad'
ybsg='yadm bisect good'
ybsr='yadm bisect reset'
ybss='yadm bisect start'
yc='yadm commit -v'
'yc!'='yadm commit -v --amend'
yca='yadm commit -v -a'
'yca!'='yadm commit -v -a --amend'
ycam='yadm commit -a -m'
'ycan!'='yadm commit -v -a --no-edit --amend'
'ycans!'='yadm commit -v -a -s --no-edit --amend'
ycb='yadm checkout -b'
ycd='yadm checkout develop'
ycf='yadm config --list'
ycl='yadm clone --recursive'
yclean='yadm clean -fd'
ycm='yadm checkout master'
ycmsg='yadm commit -m'
'ycn!'='yadm commit -v --no-edit --amend'
yco='yadm checkout'
ycount='yadm shortlog -sn'
ycp='yadm cherry-pick'
ycpa='yadm cherry-pick --abort'
ycpc='yadm cherry-pick --continue'
ycs='yadm commit -S'
ycsm='yadm commit -s -m'
yd='yadm diff'
ydca='yadm diff --cached'
ydct='yadm describe --tags `yadm rev-list --tags --max-count=1`'
ydcw='yadm diff --cached --word-diff'
ydiff='yadm diff --no-index'
ydt='yadm diff-tree --no-commit-id --name-only -r'
ydw='yadm diff --word-diff'
yf='yadm fetch'
yfa='yadm fetch --all --prune'
yfo='yadm fetch origin'
yg='yadm gui citool'
yga='yadm gui citool --amend'
ygpull='yadm pull origin $(yadm_current_branch)'
ygpush='yadm push origin $(yadm_current_branch)'
ygsup='yadm branch --set-upstream-to=origin/$(yadm_current_branch)'
yh='yadm browse'
yhh='yadm help'
yignore='yadm update-index --assume-unchanged'
yignored='yadm ls-files -v | grep "^[[:lower:]]"'
yk='\yadmk --all --branches'
yke='\yadmk --all $(yadm log -g --pretty=%h)'
yl='yadm pull'
ylg='yadm log --stat'
ylgg='yadm log --graph'
ylgga='yadm log --graph --decorate --all'
ylgm='yadm log --graph --max-count=10'
ylgp='yadm log --stat -p'
ylo='yadm log --oneline --decorate'
ylog='yadm log --oneline --decorate --graph'
yloga='yadm log --oneline --decorate --graph --all'
ylol='yadm log --graph --pretty='\''%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'' --abbrev-commit'
ylola='yadm log --graph --pretty='\''%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'' --abbrev-commit --all'
ylp=_yadm_log_prettily
ylum='yadm pull upstream master'
ym='yadm merge'
yma='yadm merge --abort'
ymom='yadm merge origin/master'
ymt='yadm mergetool --no-prompt'
ymtvim='yadm mergetool --no-prompt --tool=vimdiff'
ymum='yadm merge upstream/master'
yp='yadm push'
ypd='yadm push --dry-run'
ypoat='yadm push origin --all && yadm push origin --tags'
ypristine='yadm reset --hard && yadm clean -dfx'
ypsup='yadm push --set-upstream origin $(yadm_current_branch)'
ypu='yadm push upstream'
ypv='yadm push -v'
yr='yadm remote'
yra='yadm remote add'
yrb='yadm rebase'
yrba='yadm rebase --abort'
yrbc='yadm rebase --continue'
yrbi='yadm rebase -i'
yrbm='yadm rebase master'
yrbs='yadm rebase --skip'
yrep='grep  --color=auto --exclude-dir={.bzr,CVS,.yadm,.hg,.svn}'
yrh='yadm reset HEAD'
yrhh='yadm reset HEAD --hard'
yrmv='yadm remote rename'
yrrm='yadm remote remove'
yrset='yadm remote set-url'
yrt='cd $(yadm rev-parse --show-toplevel || echo ".")'
yru='yadm reset --'
yrup='yadm remote update'
yrv='yadm remote -v'
ysb='yadm status -sb'
ysd='yadm svn dcommit'
ysi='yadm submodule init'
ysps='yadm show --pretty=short --show-signature'
ysr='yadm svn rebase'
yss='yadm status -s'
yst='yadm status'
ysta='yadm stash save'
ystaa='yadm stash apply'
ystc='yadm stash clear'
ystd='yadm stash drop'
ystl='yadm stash list'
ystp='yadm stash pop'
ysts='yadm stash show --text'
ysu='yadm submodule update'
yts='yadm tag -s'
ytv='yadm tag | sort -V'
yunignore='yadm update-index --no-assume-unchanged'
yunwip='yadm log -n 1 | grep -q -c "\-\-wip\-\-" && yadm reset HEAD~1'
yup='yadm pull --rebase'
yupv='yadm pull --rebase -v'
ywch='yadm whatchanged -p --abbrev-commit --pretty=medium'
ywip='yadm add -A; yadm rm $(yadm ls-files --deleted) 2> /dev/null; yadm commit --no-verify -m "--wip-- [skip ci]"'
